const express = require('express')
const router = express.Router()

const CreateEmployee = require('../../controllers/CreateEmployeeController')
const CreatePet = require('../../controllers/CreatePetController')
const CreateService = require('../../controllers/CreateServicesController')
const CreateClient = require('../../controllers/CreateClientController')
const CreateMedicalAppointment = require('../../controllers/CreateMedicalAppointment')
const CreateSurgery = require('../../controllers/CreateSurgeryController')
const CreateClinicalHistory = require('../../controllers/CreateClinicalHistory')
const CreateTracking = require('../../controllers/CreateTrackingController')
const CreateProduct = require('../../controllers/CreateMedicineController')
const CreateSaleProduct = require('../../controllers/CreateProductSaleController')
const CreateSaleService = require('../../controllers/CreateServiceSaleController')
const CreatePqr = require('../../controllers/CreatePQRController')
const CreateDiagnosis = require('../../controllers/CreateDiagnosis')


const ReadIdEmployees = require('../../controllers/ReadIdEmployeeController')
const ReadAllEmployees = require('../../controllers/ReadAllEmployeeController')
const ReadPetProfile = require('../../controllers/ReadPetController')
const ReadClient = require('../../controllers/ReadClienteController')
const ReadMedicalAppointment = require('../../controllers/ReadMedicalAppointment')
const ReadSurgery = require('../../controllers/ReadSurgeryController')
const ReadSales = require('../../controllers/ReadSalesController')
const ReadMedicine = require('../../controllers/ReadMedicineController')
const ReadService = require('../../controllers/ReadServicesController')
const ReadPqr = require('../../controllers/ReadPQRController')

const UpdateClient = require('../../controllers/UpdateClientController')
const UpdateClinicalHistory = require('../../controllers/UpdateClinicalHistoryController')
const UpdateMedicalAppointment = require('../../controllers/UpdateMedicalAppointmentController')
const UpdatePetProfileController = require('../../controllers/UpdatePetController')
const UpdatePQR = require('../../controllers/UpdatePQRController')
const UpdateProduct = require('../../controllers/UpdateMedicineController')
const UpdateSaleProduct = require('../../controllers/UpdateProductSaleController')
const UpdateServiceSale = require('../../controllers/UpdateServiceSaleController')
const UpdateService = require('../../controllers/UpdateServicesController')
const UpdateSurgery = require('../../controllers/UpdateSurgeryController')
const UpdateUser = require('../../controllers/UpdateEmployeeController')


router  
    // Crear
    .post('/register/employee',CreateEmployee)  
    .post('/register/pet',CreatePet)
    .post('/register/client',CreateClient)
    .post('/register/service',CreateService)
    .post('/register/medical-appointment',CreateMedicalAppointment)
    .post('/register/surgery',CreateSurgery)
    .post('/register/clinical-history',CreateClinicalHistory)
    .post('/register/tracking',CreateTracking)
    .post('/register/product',CreateProduct)
    .post('/register/sales/product',CreateSaleProduct)
    .post('/register/sales/service',CreateSaleService)
    .post('/register/pqr',CreatePqr)
    .post('/register/diagnostico',CreateDiagnosis)

    // Visualizar
    .get('/list/pet/:id',ReadPetProfile.ReadIdPetProfile)
    .get('/list/client/:id',ReadClient.ReadIdClient)
    .get('/list/medical-appointment/:id',ReadMedicalAppointment.ReadIdMedicalAppointment)
    .get('/list/surgery/:id',ReadSurgery.ReadIdSurgery)
    .get('/list/sales/product/:id',ReadSales.ReadIdProductSale)
    .get('/list/sales/service/:id',ReadSales.ReadIdServiceSale)
    .get('/list/service/:id',ReadService.ReadIdService)
    .get('/list/product/:id',ReadMedicine.ReadIdProduct)
    .get('/list/pqr/:id',ReadPqr.ReadIdPQR)
    .get('/list/employee/:id',ReadIdEmployees.ReadIdEmployee)
    .get('/list/medical/:id',ReadIdEmployees.ReadIdMedical)
    .get('/list/auxiliary/:id',ReadIdEmployees.ReadIdAuxiliaries)
    .get('/list/receptionist/:id',ReadIdEmployees.ReadIdReceptionists)

    // Modificar 
    .put('/edit/user/:id',UpdateUser)
    .put('/edit/pet/:id',UpdatePetProfileController)
    .put('/edit/client/:id',UpdateClient)
    .put('/edit/medical-appointment/:id',UpdateMedicalAppointment)
    .put('/edit/surgery/:id',UpdateSurgery)
    .put('/edit/sale/product/:id',UpdateSaleProduct)
    .put('/edit/sale/service/:id',UpdateServiceSale)
    .put('/edit/service/:id',UpdateService)
    .put('/edit/product/:id',UpdateProduct)
    .put('/edit/pqr/:id',UpdatePQR)
    .put('/edit/clinical-history/:id',UpdateClinicalHistory)

    // Listar
    .get('/list/medicals',ReadAllEmployees.ReadAllMedical)
    .get('/list/auxiliaries',ReadAllEmployees.ReadAllAuxiliaries)
    .get('/list/receptionists',ReadAllEmployees.ReadAllReceptionists)
    .get('/list/employees/all',ReadAllEmployees.ReadAllEmployees)
    .get('/list/pet/all',ReadPetProfile.ReadAllPetProfile)
    .get('/list/clients/all',ReadClient.ReadAllClient)
    .get('/list/medical-appointment/all',ReadMedicalAppointment.ReadAllMedicalAppointment)
    .get('/list/surgery/all',ReadSurgery.ReadAllSurgery)
    .get('/list/sales/product/all',ReadSales.ReadAllProductSale)
    .get('/list/sales/service/all',ReadSales.ReadAllServiceSale)
    .get('/list/product/all',ReadMedicine.ReadAllMedicine)
    .get('/list/service/all',ReadService.ReadAllService)
    .get('/list/pqr/all',ReadPqr.ReadAllPQR)


module.exports = router